### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by djoudi** [manishkatyan/bbb-mp4-old#3]
node bbb-mp4 592e0be2dce4fb658033b26ad86778c9f65bebd2-1609669841386
Fetching: https://domainname.com/playback/presentation/2.3/592e0be2dce4fb658033b26ad86738c9f65bebd2-1609669841386
Error: Evaluation failed: TypeError: Cannot read property 'textContent' of null
    at __puppeteer_evaluation_script__:2:51
    at ExecutionContext._evaluateInternal (/home/user/bbb-mp4/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (/home/user/bbb-mp4/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async main (/home/user/bbb-mp4/bbb-mp4.js:90:19)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/user/bbb-mp4/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.evaluate (/home/user/bbb-mp4/node_modules/puppeteer/lib/DOMWorld.js:112:20)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/user/bbb-mp4/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.evaluate (/home/user/bbb-mp4/node_modules/puppeteer/lib/Page.js:860:43)
    at Page.<anonymous> (/home/user/bbb-mp4/node_modules/puppeteer/lib/helper.js:112:23)
    at main (/home/user/bbb-mp4/bbb-mp4.js:90:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by djoudi** [comment]
@manishkatyan

**Comment by manishkatyan** [comment]
I will check and revert soon

**Comment by djoudi** [comment]
@manishkatyan 
thanks waiting ..

**Comment by manishkatyan** [comment]
Hi,

You are trying to use 2.3 player. Click on the your URL - https://domainname.com/playback/presentation/2.3/592e0be2dce4fb658033b26ad86738c9f65bebd2-1609669841386 - it's not opening.

It means first you need to install 2.3 player - https://github.com/bigbluebutton/bbb-playback

**Comment by djoudi** [comment]
> lick on the your UR

this link without real domain is just example 
https://domainname.com/playback/presentation/2.3/592e0be2dce4fb658033b26ad86738c9f65bebd2-1609669841386
