### ISSUE TITLE
ENOTEMPTY: directory not empty,

### ISSUE THREAD

**Issue by borhanreo** [manishkatyan/bbb-mp4-old#6]
```
fs.js:846
  return binding.rmdir(pathModule._makeLong(path));
                 ^

Error: ENOTEMPTY: directory not empty, rmdir '/root/bbb-mp4-old/webm/a370c0cbed7805985f854defeba03b4001cbc252-1614574387916'
    at Object.fs.rmdirSync (fs.js:846:18)
    at ChildProcess.ls.on (/root/bbb-mp4-old/bbb-mp4.js:191:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

**Comment by borhanreo** [comment]
issue fixed. It's an node version issue

**Comment by borhanreo** [comment]
issue solve
